import json

NEW_WORDS = [
  # Days of week
  {"swedish":"måndag","german":"Montag","example":"På måndag börjar skolan.","exampleTranslation":"Am Montag beginnt die Schule."},
  {"swedish":"tisdag","german":"Dienstag","example":"Vi träffas på tisdag.","exampleTranslation":"Wir treffen uns am Dienstag."},
  {"swedish":"onsdag","german":"Mittwoch","example":"Onsdag är mitt i veckan.","exampleTranslation":"Mittwoch ist mitten in der Woche."},
  {"swedish":"torsdag","german":"Donnerstag","example":"Torsdag är snart fredag.","exampleTranslation":"Donnerstag ist fast Freitag."},
  {"swedish":"fredag","german":"Freitag","example":"På fredag är det fest.","exampleTranslation":"Am Freitag ist eine Party."},
  {"swedish":"lördag","german":"Samstag","example":"Vi städar på lördag.","exampleTranslation":"Wir putzen am Samstag."},
  {"swedish":"söndag","german":"Sonntag","example":"Söndag är en vilodadag.","exampleTranslation":"Sonntag ist ein Ruhetag."},
  # Time
  {"swedish":"morgon","german":"Morgen","example":"God morgon! Jag dricker kaffe på morgonen.","exampleTranslation":"Guten Morgen! Ich trinke Kaffee am Morgen."},
  {"swedish":"eftermiddag","german":"Nachmittag","example":"Vi ses på eftermiddagen.","exampleTranslation":"Wir sehen uns am Nachmittag."},
  {"swedish":"kväll","german":"Abend","example":"På kvällen tittar vi på TV.","exampleTranslation":"Am Abend schauen wir Fernsehen."},
  {"swedish":"midnatt","german":"Mitternacht","example":"Festen slutar vid midnatt.","exampleTranslation":"Die Party endet um Mitternacht."},
  {"swedish":"halv","german":"halb","example":"Klockan är halv tre.","exampleTranslation":"Es ist halb drei."},
  {"swedish":"kvart","german":"Viertel","example":"Klockan är kvart över fem.","exampleTranslation":"Es ist Viertel nach fünf."},
  {"swedish":"sekund","german":"Sekunde","example":"Vänta en sekund!","exampleTranslation":"Warte eine Sekunde!"},
  {"swedish":"noll","german":"null / Null","example":"Noll är inte ett positivt tal.","exampleTranslation":"Null ist keine positive Zahl."},
  {"swedish":"tid","german":"Zeit","example":"Har du tid nu?","exampleTranslation":"Hast du jetzt Zeit?"},
  {"swedish":"schema","german":"Stundenplan / Zeitplan","example":"Mitt schema är fullt idag.","exampleTranslation":"Mein Stundenplan ist heute voll."},
  # Body parts
  {"swedish":"huvud","german":"Kopf","example":"Jag har ont i huvudet.","exampleTranslation":"Ich habe Kopfschmerzen."},
  {"swedish":"öga","german":"Auge","example":"Hon har blå ögon.","exampleTranslation":"Sie hat blaue Augen."},
  {"swedish":"öra","german":"Ohr","example":"Jag hör dåligt på höger öra.","exampleTranslation":"Ich höre schlecht auf dem rechten Ohr."},
  {"swedish":"näsa","german":"Nase","example":"Min näsa rinner.","exampleTranslation":"Meine Nase läuft."},
  {"swedish":"mun","german":"Mund","example":"Öppna munnen!","exampleTranslation":"Öffne den Mund!"},
  {"swedish":"tand","german":"Zahn","example":"Du måste borsta tänderna.","exampleTranslation":"Du musst die Zähne putzen."},
  {"swedish":"arm","german":"Arm","example":"Jag har brutit armen.","exampleTranslation":"Ich habe mir den Arm gebrochen."},
  {"swedish":"ben","german":"Bein","example":"Hunden springer på fyra ben.","exampleTranslation":"Der Hund läuft auf vier Beinen."},
  {"swedish":"hand","german":"Hand","example":"Ge mig din hand.","exampleTranslation":"Gib mir deine Hand."},
  {"swedish":"finger","german":"Finger","example":"Jag har tio fingrar.","exampleTranslation":"Ich habe zehn Finger."},
  {"swedish":"nacke","german":"Nacken / Hals","example":"Jag har ont i nacken.","exampleTranslation":"Ich habe Nackenschmerzen."},
  {"swedish":"axel","german":"Schulter","example":"Han lyfter med axlarna.","exampleTranslation":"Er zuckt mit den Schultern."},
  {"swedish":"knä","german":"Knie","example":"Barnet slog sig i knät.","exampleTranslation":"Das Kind hat sich das Knie gestoßen."},
  {"swedish":"bröst","german":"Brust","example":"Han har ont i bröstet.","exampleTranslation":"Er hat Brustschmerzen."},
  {"swedish":"ansikte","german":"Gesicht","example":"Tvätta ansiktet på morgonen.","exampleTranslation":"Wasch das Gesicht am Morgen."},
  {"swedish":"hår","german":"Haar","example":"Hon har långt hår.","exampleTranslation":"Sie hat langes Haar."},
  {"swedish":"hud","german":"Haut","example":"Min hud är torr på vintern.","exampleTranslation":"Meine Haut ist im Winter trocken."},
  # Rooms / home
  {"swedish":"vardagsrum","german":"Wohnzimmer","example":"Vi sitter i vardagsrummet.","exampleTranslation":"Wir sitzen im Wohnzimmer."},
  {"swedish":"sovrum","german":"Schlafzimmer","example":"Sovrummet är litet men mysigt.","exampleTranslation":"Das Schlafzimmer ist klein aber gemütlich."},
  {"swedish":"hall","german":"Flur / Diele","example":"Hängt jackan i hallen.","exampleTranslation":"Häng die Jacke im Flur auf."},
  {"swedish":"trädgård","german":"Garten","example":"Barnen leker i trädgården.","exampleTranslation":"Die Kinder spielen im Garten."},
  {"swedish":"trappa","german":"Treppe","example":"Gå upp för trappan.","exampleTranslation":"Geh die Treppe hinauf."},
  {"swedish":"golv","german":"Fußboden / Boden","example":"Golvet är kallt på vintern.","exampleTranslation":"Der Boden ist im Winter kalt."},
  {"swedish":"tak","german":"Decke / Dach","example":"Taket i rummet är högt.","exampleTranslation":"Die Decke im Zimmer ist hoch."},
  {"swedish":"vägg","german":"Wand","example":"Det hänger en tavla på väggen.","exampleTranslation":"An der Wand hängt ein Bild."},
  {"swedish":"balkong","german":"Balkon","example":"Vi dricker kaffe på balkongen.","exampleTranslation":"Wir trinken Kaffee auf dem Balkon."},
  {"swedish":"källare","german":"Keller","example":"Vi förvarar cykeln i källaren.","exampleTranslation":"Wir lagern das Fahrrad im Keller."},
  # Household items
  {"swedish":"skåp","german":"Schrank","example":"Kläderna ligger i skåpet.","exampleTranslation":"Die Kleidung liegt im Schrank."},
  {"swedish":"hylla","german":"Regal","example":"Böckerna står på hyllan.","exampleTranslation":"Die Bücher stehen im Regal."},
  {"swedish":"matta","german":"Teppich","example":"Det ligger en matta på golvet.","exampleTranslation":"Auf dem Boden liegt ein Teppich."},
  {"swedish":"gardin","german":"Vorhang / Gardine","example":"Drag igen gardinerna.","exampleTranslation":"Zieh die Vorhänge zu."},
  {"swedish":"kudde","german":"Kissen","example":"Jag sover med två kuddar.","exampleTranslation":"Ich schlafe mit zwei Kissen."},
  {"swedish":"täcke","german":"Bettdecke","example":"Det är kallt, ta täcket!","exampleTranslation":"Es ist kalt, nimm die Decke!"},
  {"swedish":"kylskåp","german":"Kühlschrank","example":"Mjölken finns i kylskåpet.","exampleTranslation":"Die Milch ist im Kühlschrank."},
  {"swedish":"spis","german":"Herd","example":"Maten kokar på spisen.","exampleTranslation":"Das Essen kocht auf dem Herd."},
  {"swedish":"ugn","german":"Backofen / Ofen","example":"Kakan är i ugnen.","exampleTranslation":"Der Kuchen ist im Ofen."},
  {"swedish":"diskmaskin","german":"Geschirrspüler","example":"Stoppa in disken i diskmaskinen.","exampleTranslation":"Stell das Geschirr in den Geschirrspüler."},
  {"swedish":"tvättmaskin","german":"Waschmaschine","example":"Tvätten är klar i tvättmaskinen.","exampleTranslation":"Die Wäsche ist in der Waschmaschine fertig."},
  {"swedish":"dusch","german":"Dusche","example":"Jag tar en dusch varje dag.","exampleTranslation":"Ich dusche jeden Tag."},
  {"swedish":"badkar","german":"Badewanne","example":"Barnen badar i badkaret.","exampleTranslation":"Die Kinder baden in der Badewanne."},
  {"swedish":"spegel","german":"Spiegel","example":"Titta i spegeln!","exampleTranslation":"Schau in den Spiegel!"},
  {"swedish":"handduk","german":"Handtuch","example":"Kan jag låna en handduk?","exampleTranslation":"Kann ich ein Handtuch ausleihen?"},
  {"swedish":"tvål","german":"Seife","example":"Tvätta händerna med tvål.","exampleTranslation":"Wasch die Hände mit Seife."},
  {"swedish":"tandborste","german":"Zahnbürste","example":"Jag glömde min tandborste.","exampleTranslation":"Ich habe meine Zahnbürste vergessen."},
  {"swedish":"tandkräm","german":"Zahnpasta","example":"Jag behöver mer tandkräm.","exampleTranslation":"Ich brauche mehr Zahnpasta."},
  {"swedish":"handfat","german":"Waschbecken","example":"Handfatet är igensatt.","exampleTranslation":"Das Waschbecken ist verstopft."},
  {"swedish":"papperskorg","german":"Papierkorb","example":"Kasta det i papperskorgen.","exampleTranslation":"Wirf es in den Papierkorb."},
  # Clothing
  {"swedish":"skjorta","german":"Hemd","example":"Han bär en vit skjorta.","exampleTranslation":"Er trägt ein weißes Hemd."},
  {"swedish":"byxor","german":"Hose","example":"Jeans är ett slags byxor.","exampleTranslation":"Jeans sind eine Art Hose."},
  {"swedish":"kjol","german":"Rock","example":"Hon har på sig en röd kjol.","exampleTranslation":"Sie trägt einen roten Rock."},
  {"swedish":"klänning","german":"Kleid","example":"Hon är klädd i en blå klänning.","exampleTranslation":"Sie trägt ein blaues Kleid."},
  {"swedish":"jacka","german":"Jacke","example":"Ta på dig jackan, det är kallt.","exampleTranslation":"Zieh die Jacke an, es ist kalt."},
  {"swedish":"kappa","german":"Mantel","example":"Hennes kappa är varm.","exampleTranslation":"Ihr Mantel ist warm."},
  {"swedish":"tröja","german":"Pullover / Sweatshirt","example":"Jag har en grön tröja.","exampleTranslation":"Ich habe einen grünen Pullover."},
  {"swedish":"strumpor","german":"Socken / Strümpfe","example":"Mina strumpor är blöta.","exampleTranslation":"Meine Socken sind nass."},
  {"swedish":"skor","german":"Schuhe","example":"Dessa skor är för stora.","exampleTranslation":"Diese Schuhe sind zu groß."},
  {"swedish":"stövlar","german":"Stiefel","example":"Hon bär gummistövlar i regnet.","exampleTranslation":"Sie trägt Gummistiefel im Regen."},
  {"swedish":"mössa","german":"Mütze","example":"Ta på dig mössan, det snöar.","exampleTranslation":"Setz die Mütze auf, es schneit."},
  {"swedish":"vantar","german":"Fäustlinge / Handschuhe","example":"Glöm inte vantarna!","exampleTranslation":"Vergiss die Handschuhe nicht!"},
  {"swedish":"halsduk","german":"Schal","example":"En varm halsduk hjälper mot kylan.","exampleTranslation":"Ein warmer Schal hilft gegen die Kälte."},
  {"swedish":"glasögon","german":"Brille","example":"Jag behöver glasögon för att läsa.","exampleTranslation":"Ich brauche eine Brille zum Lesen."},
  {"swedish":"ring","german":"Ring","example":"Hon bär en ring på fingret.","exampleTranslation":"Sie trägt einen Ring am Finger."},
  {"swedish":"halsband","german":"Halskette","example":"Hon fick ett halsband i present.","exampleTranslation":"Sie bekam eine Halskette als Geschenk."},
  {"swedish":"hatt","german":"Hut","example":"Han har en svart hatt.","exampleTranslation":"Er hat einen schwarzen Hut."},
  {"swedish":"kläder","german":"Kleidung","example":"Vilka kläder ska jag ta med?","exampleTranslation":"Welche Kleidung soll ich mitnehmen?"},
  {"swedish":"storlek","german":"Größe","example":"Vilken storlek har du?","exampleTranslation":"Welche Größe hast du?"},
  {"swedish":"mode","german":"Mode","example":"Hon är intresserad av mode.","exampleTranslation":"Sie interessiert sich für Mode."},
  # Food & drink
  {"swedish":"juice","german":"Saft / Juice","example":"Jag dricker apelsinjuice.","exampleTranslation":"Ich trinke Orangensaft."},
  {"swedish":"öl","german":"Bier","example":"Han dricker en kall öl.","exampleTranslation":"Er trinkt ein kaltes Bier."},
  {"swedish":"vin","german":"Wein","example":"Vi dricker vin till maten.","exampleTranslation":"Wir trinken Wein zum Essen."},
  {"swedish":"choklad","german":"Schokolade","example":"Jag älskar choklad.","exampleTranslation":"Ich liebe Schokolade."},
  {"swedish":"glass","german":"Eis / Eiscreme","example":"Vi äter glass på sommaren.","exampleTranslation":"Wir essen im Sommer Eis."},
  {"swedish":"kaka","german":"Keks / Kuchen","example":"Farmor bakar kakor.","exampleTranslation":"Oma backt Kuchen."},
  {"swedish":"tårta","german":"Torte / Kuchen","example":"Vi äter tårta på födelsedagen.","exampleTranslation":"Wir essen Torte zum Geburtstag."},
  {"swedish":"pasta","german":"Pasta / Nudeln","example":"Jag lagar pasta till middag.","exampleTranslation":"Ich koche Nudeln zum Abendessen."},
  {"swedish":"sallad","german":"Salat","example":"Jag äter sallad varje dag.","exampleTranslation":"Ich esse jeden Tag Salat."},
  {"swedish":"lök","german":"Zwiebel","example":"Löken gör att jag gråter.","exampleTranslation":"Die Zwiebel bringt mich zum Weinen."},
  {"swedish":"morot","german":"Karotte / Möhre","example":"Kaninen äter morötter.","exampleTranslation":"Das Kaninchen frisst Karotten."},
  {"swedish":"gurka","german":"Gurke","example":"Jag vill ha gurka i salladen.","exampleTranslation":"Ich möchte Gurke im Salat."},
  {"swedish":"paprika","german":"Paprika","example":"Röd paprika är söt.","exampleTranslation":"Rote Paprika ist süß."},
  {"swedish":"päron","german":"Birne","example":"Päronet är saftigt och gott.","exampleTranslation":"Die Birne ist saftig und lecker."},
  {"swedish":"jordgubbe","german":"Erdbeere","example":"Jordgubbar med grädde är gott.","exampleTranslation":"Erdbeeren mit Sahne sind lecker."},
  {"swedish":"hallon","german":"Himbeere","example":"Hallonen är röda och söta.","exampleTranslation":"Himbeeren sind rot und süß."},
  {"swedish":"blåbär","german":"Blaubeere / Heidelbeere","example":"Vi plockar blåbär i skogen.","exampleTranslation":"Wir pflücken Blaubeeren im Wald."},
  {"swedish":"svamp","german":"Pilz","example":"Vi plockar svamp på hösten.","exampleTranslation":"Wir sammeln Pilze im Herbst."},
  {"swedish":"salt","german":"Salz","example":"Maten behöver mer salt.","exampleTranslation":"Das Essen braucht mehr Salz."},
  {"swedish":"peppar","german":"Pfeffer","example":"Kan jag få peppar?","exampleTranslation":"Kann ich den Pfeffer haben?"},
  {"swedish":"olja","german":"Öl (Speiseöl)","example":"Stek löken i lite olja.","exampleTranslation":"Brate die Zwiebel in etwas Öl."},
  {"swedish":"honung","german":"Honig","example":"Jag har honung i teet.","exampleTranslation":"Ich habe Honig im Tee."},
  {"swedish":"smörgås","german":"belegtes Brot / Butterbrot","example":"Jag äter en smörgås till lunch.","exampleTranslation":"Ich esse ein belegtes Brot zum Mittagessen."},
  {"swedish":"nötter","german":"Nüsse","example":"Nötter är nyttiga att äta.","exampleTranslation":"Nüsse sind gesund zu essen."},
  {"swedish":"bönor","german":"Bohnen","example":"Vi äter bönor med ris.","exampleTranslation":"Wir essen Bohnen mit Reis."},
  {"swedish":"majs","german":"Mais","example":"Vi grillar majs på sommaren.","exampleTranslation":"Wir grillen Mais im Sommer."},
  {"swedish":"lemonad","german":"Limonade","example":"Barnen dricker lemonad.","exampleTranslation":"Die Kinder trinken Limonade."},
  {"swedish":"grädde","german":"Sahne / Rahm","example":"Jordgubbar med grädde är gott.","exampleTranslation":"Erdbeeren mit Sahne sind lecker."},
  {"swedish":"sylt","german":"Marmelade / Konfitüre","example":"Jag vill ha sylt på brödet.","exampleTranslation":"Ich möchte Marmelade auf dem Brot."},
  {"swedish":"senap","german":"Senf","example":"Jag vill ha senap på korven.","exampleTranslation":"Ich möchte Senf auf der Wurst."},
  # Verbs
  {"swedish":"att skriva","german":"schreiben","example":"Jag skriver ett brev.","exampleTranslation":"Ich schreibe einen Brief."},
  {"swedish":"att rita","german":"zeichnen","example":"Barnet ritar en sol.","exampleTranslation":"Das Kind zeichnet eine Sonne."},
  {"swedish":"att sjunga","german":"singen","example":"Hon sjunger vackert.","exampleTranslation":"Sie singt schön."},
  {"swedish":"att dansa","german":"tanzen","example":"Vi dansar på festen.","exampleTranslation":"Wir tanzen auf der Party."},
  {"swedish":"att laga","german":"kochen / reparieren","example":"Pappa lagar mat varje dag.","exampleTranslation":"Papa kocht jeden Tag."},
  {"swedish":"att tvätta","german":"waschen","example":"Jag tvättar kläderna.","exampleTranslation":"Ich wasche die Kleidung."},
  {"swedish":"att städa","german":"putzen / aufräumen","example":"Vi städar lägenheten på lördag.","exampleTranslation":"Wir putzen die Wohnung am Samstag."},
  {"swedish":"att ringa","german":"anrufen / klingeln","example":"Ring mig imorgon!","exampleTranslation":"Ruf mich morgen an!"},
  {"swedish":"att träffa","german":"treffen","example":"Vi träffas klockan tre.","exampleTranslation":"Wir treffen uns um drei Uhr."},
  {"swedish":"att börja","german":"anfangen / beginnen","example":"Filmen börjar klockan sju.","exampleTranslation":"Der Film beginnt um sieben Uhr."},
  {"swedish":"att sluta","german":"aufhören / enden","example":"Skolan slutar klockan tre.","exampleTranslation":"Die Schule endet um drei Uhr."},
  {"swedish":"att stanna","german":"bleiben / anhalten","example":"Stanna! Vänta på mig!","exampleTranslation":"Halt! Warte auf mich!"},
  {"swedish":"att vänta","german":"warten","example":"Vänta lite, jag kommer!","exampleTranslation":"Warte kurz, ich komme!"},
  {"swedish":"att köra","german":"fahren (Auto)","example":"Han kör bil till jobbet.","exampleTranslation":"Er fährt mit dem Auto zur Arbeit."},
  {"swedish":"att resa","german":"reisen","example":"Vi reser till Spanien.","exampleTranslation":"Wir reisen nach Spanien."},
  {"swedish":"att besöka","german":"besuchen","example":"Vi besöker mormor på söndag.","exampleTranslation":"Wir besuchen Oma am Sonntag."},
  {"swedish":"att hitta","german":"finden","example":"Jag kan inte hitta mina nycklar.","exampleTranslation":"Ich kann meine Schlüssel nicht finden."},
  {"swedish":"att förlora","german":"verlieren","example":"Jag har förlorat min plånbok.","exampleTranslation":"Ich habe mein Portemonnaie verloren."},
  {"swedish":"att bära","german":"tragen","example":"Kan du bära väskan?","exampleTranslation":"Kannst du die Tasche tragen?"},
  {"swedish":"att hoppa","german":"hüpfen / springen","example":"Barnen hoppar på studsmattan.","exampleTranslation":"Die Kinder hüpfen auf dem Trampolin."},
  {"swedish":"att falla","german":"fallen","example":"Akta dig så du inte faller!","exampleTranslation":"Pass auf, dass du nicht fällst!"},
  {"swedish":"att vakna","german":"aufwachen","example":"Jag vaknar klockan sju.","exampleTranslation":"Ich wache um sieben Uhr auf."},
  {"swedish":"att le","german":"lächeln","example":"Hon ler alltid.","exampleTranslation":"Sie lächelt immer."},
  {"swedish":"att skratta","german":"lachen","example":"Vi skrattar åt filmen.","exampleTranslation":"Wir lachen über den Film."},
  {"swedish":"att gråta","german":"weinen","example":"Barnet gråter.","exampleTranslation":"Das Kind weint."},
  {"swedish":"att kyssa","german":"küssen","example":"De kysser varandra.","exampleTranslation":"Sie küssen sich."},
  {"swedish":"att krama","german":"umarmen","example":"Hon kramas med sin mamma.","exampleTranslation":"Sie umarmt ihre Mutter."},
  {"swedish":"att fråga","german":"fragen","example":"Får jag fråga dig något?","exampleTranslation":"Darf ich dich etwas fragen?"},
  {"swedish":"att svara","german":"antworten","example":"Svara på min fråga!","exampleTranslation":"Antworte auf meine Frage!"},
  {"swedish":"att berätta","german":"erzählen","example":"Berätta om din dag!","exampleTranslation":"Erzähl mir von deinem Tag!"},
  {"swedish":"att kosta","german":"kosten","example":"Vad kostar det?","exampleTranslation":"Was kostet das?"},
  {"swedish":"att sälja","german":"verkaufen","example":"De säljer frukt på torget.","exampleTranslation":"Sie verkaufen Obst auf dem Marktplatz."},
  {"swedish":"att byta","german":"wechseln / tauschen","example":"Kan jag byta den här?","exampleTranslation":"Kann ich das hier umtauschen?"},
  {"swedish":"att åka","german":"fahren / reisen","example":"Vi åker tåg till Stockholm.","exampleTranslation":"Wir fahren mit dem Zug nach Stockholm."},
  {"swedish":"att gilla","german":"mögen / gefallen","example":"Jag gillar choklad.","exampleTranslation":"Ich mag Schokolade."},
  {"swedish":"att hoppas","german":"hoffen","example":"Jag hoppas det blir fint väder.","exampleTranslation":"Ich hoffe, das Wetter wird schön."},
  {"swedish":"att tro","german":"glauben / denken","example":"Jag tror han kommer snart.","exampleTranslation":"Ich glaube, er kommt bald."},
  {"swedish":"att minnas","german":"sich erinnern","example":"Jag minns inte hennes namn.","exampleTranslation":"Ich erinnere mich nicht an ihren Namen."},
  {"swedish":"att glömma","german":"vergessen","example":"Glöm inte din väska!","exampleTranslation":"Vergiss deine Tasche nicht!"},
  {"swedish":"att lära sig","german":"lernen","example":"Jag lär mig svenska.","exampleTranslation":"Ich lerne Schwedisch."},
  {"swedish":"att känna","german":"fühlen / kennen","example":"Känner du honom?","exampleTranslation":"Kennst du ihn?"},
  {"swedish":"att använda","german":"benutzen / verwenden","example":"Jag använder datorn varje dag.","exampleTranslation":"Ich benutze den Computer jeden Tag."},
  {"swedish":"att dela","german":"teilen","example":"Vi delar maten.","exampleTranslation":"Wir teilen das Essen."},
  {"swedish":"att skicka","german":"schicken / senden","example":"Kan du skicka mig ett mejl?","exampleTranslation":"Kannst du mir eine E-Mail schicken?"},
  {"swedish":"att ta emot","german":"empfangen / erhalten","example":"Jag tar emot paketet imorgon.","exampleTranslation":"Ich erhalte das Paket morgen."},
  {"swedish":"att välja","german":"wählen / auswählen","example":"Välj din favoritmåltid!","exampleTranslation":"Wähle dein Lieblingsessen!"},
  {"swedish":"att vinna","german":"gewinnen","example":"Vilket lag vinner?","exampleTranslation":"Welches Team gewinnt?"},
  {"swedish":"att stå","german":"stehen","example":"Han står vid dörren.","exampleTranslation":"Er steht an der Tür."},
  {"swedish":"att sitta","german":"sitzen","example":"Vi sitter runt bordet.","exampleTranslation":"Wir sitzen um den Tisch."},
  {"swedish":"att ligga","german":"liegen","example":"Boken ligger på golvet.","exampleTranslation":"Das Buch liegt auf dem Boden."},
  # Adjectives
  {"swedish":"fri","german":"frei","example":"I helgen är jag fri.","exampleTranslation":"Am Wochenende bin ich frei."},
  {"swedish":"hög","german":"hoch","example":"Berget är högt.","exampleTranslation":"Der Berg ist hoch."},
  {"swedish":"låg","german":"niedrig","example":"Priset är lågt idag.","exampleTranslation":"Der Preis ist heute niedrig."},
  {"swedish":"tjock","german":"dick","example":"Boken är tjock.","exampleTranslation":"Das Buch ist dick."},
  {"swedish":"tunn","german":"dünn","example":"Isen är tunn, gå inte ut!","exampleTranslation":"Das Eis ist dünn, geh nicht raus!"},
  {"swedish":"tung","german":"schwer (Gewicht)","example":"Väskan är tung.","exampleTranslation":"Die Tasche ist schwer."},
  {"swedish":"mjuk","german":"weich","example":"Kudden är mjuk.","exampleTranslation":"Das Kissen ist weich."},
  {"swedish":"trång","german":"eng / schmal","example":"Klänningen är trång.","exampleTranslation":"Das Kleid ist eng."},
  {"swedish":"bred","german":"breit","example":"Vägen är bred.","exampleTranslation":"Die Straße ist breit."},
  {"swedish":"djup","german":"tief","example":"Sjön är djup.","exampleTranslation":"Der See ist tief."},
  {"swedish":"ung","german":"jung","example":"Hon är ung och energisk.","exampleTranslation":"Sie ist jung und energisch."},
  {"swedish":"ful","german":"hässlich","example":"Vädret är fult idag.","exampleTranslation":"Das Wetter ist heute hässlich."},
  {"swedish":"tyst","german":"still / leise","example":"Var tyst! Barnet sover.","exampleTranslation":"Sei ruhig! Das Kind schläft."},
  {"swedish":"stark","german":"stark","example":"Han är mycket stark.","exampleTranslation":"Er ist sehr stark."},
  {"swedish":"svag","german":"schwach","example":"Jag är svag efter sjukdomen.","exampleTranslation":"Ich bin nach der Krankheit schwach."},
  {"swedish":"farlig","german":"gefährlich","example":"Det är farligt att simma här.","exampleTranslation":"Es ist gefährlich, hier zu schwimmen."},
  {"swedish":"trygg","german":"sicher / geborgen","example":"Barnet är tryggt med sin mamma.","exampleTranslation":"Das Kind fühlt sich bei seiner Mutter geborgen."},
  {"swedish":"viktig","german":"wichtig","example":"Det är viktigt att äta frukost.","exampleTranslation":"Es ist wichtig, Frühstück zu essen."},
  {"swedish":"intressant","german":"interessant","example":"Boken är intressant.","exampleTranslation":"Das Buch ist interessant."},
  {"swedish":"underbar","german":"wunderbar","example":"Det är underbart väder idag!","exampleTranslation":"Das Wetter ist heute wunderbar!"},
  {"swedish":"hemsk","german":"schrecklich / furchtbar","example":"Det var en hemsk film.","exampleTranslation":"Es war ein schrecklicher Film."},
  {"swedish":"lycklig","german":"glücklich","example":"Hon är lycklig i sitt arbete.","exampleTranslation":"Sie ist glücklich in ihrer Arbeit."},
  {"swedish":"arg","german":"wütend / böse","example":"Han är arg på mig.","exampleTranslation":"Er ist wütend auf mich."},
  {"swedish":"rädd","german":"ängstlich / Angst haben","example":"Jag är rädd för spindlar.","exampleTranslation":"Ich habe Angst vor Spinnen."},
  {"swedish":"orolig","german":"besorgt / unruhig","example":"Hon är orolig för barnet.","exampleTranslation":"Sie ist besorgt um das Kind."},
  {"swedish":"förvånad","german":"erstaunt / überrascht","example":"Jag var förvånad över nyheten.","exampleTranslation":"Ich war über die Neuigkeit überrascht."},
  {"swedish":"mätt","german":"satt / voll (nach dem Essen)","example":"Tack, jag är mätt.","exampleTranslation":"Danke, ich bin satt."},
  {"swedish":"nervös","german":"nervös","example":"Jag är nervös inför provet.","exampleTranslation":"Ich bin vor der Prüfung nervös."},
  {"swedish":"snygg","german":"gut aussehend / schick","example":"Hon är snygg och smart.","exampleTranslation":"Sie ist gut aussehend und klug."},
  {"swedish":"nöjd","german":"zufrieden","example":"Jag är nöjd med resultatet.","exampleTranslation":"Ich bin mit dem Ergebnis zufrieden."},
  # Places in town
  {"swedish":"park","german":"Park","example":"Barnen leker i parken.","exampleTranslation":"Die Kinder spielen im Park."},
  {"swedish":"bibliotek","german":"Bibliothek","example":"Jag lånar böcker på biblioteket.","exampleTranslation":"Ich leihe Bücher in der Bibliothek aus."},
  {"swedish":"sjukhus","german":"Krankenhaus","example":"Han är inlagd på sjukhuset.","exampleTranslation":"Er liegt im Krankenhaus."},
  {"swedish":"apotek","german":"Apotheke","example":"Jag köper medicin på apoteket.","exampleTranslation":"Ich kaufe Medizin in der Apotheke."},
  {"swedish":"restaurang","german":"Restaurant","example":"Vi äter på restaurang på lördag.","exampleTranslation":"Wir essen am Samstag im Restaurant."},
  {"swedish":"café","german":"Café","example":"Vi fikar på ett café.","exampleTranslation":"Wir trinken Kaffee in einem Café."},
  {"swedish":"hotell","german":"Hotel","example":"Vi bor på hotell under resan.","exampleTranslation":"Wir wohnen während der Reise im Hotel."},
  {"swedish":"flygplats","german":"Flughafen","example":"Flyget avgår från flygplatsen.","exampleTranslation":"Das Flugzeug fliegt vom Flughafen ab."},
  {"swedish":"station","german":"Bahnhof","example":"Tåget stannar vid stationen.","exampleTranslation":"Der Zug hält am Bahnhof."},
  {"swedish":"hamn","german":"Hafen","example":"Båten ligger i hamnen.","exampleTranslation":"Das Boot liegt im Hafen."},
  {"swedish":"kyrka","german":"Kirche","example":"Kyrkan är gammal och vacker.","exampleTranslation":"Die Kirche ist alt und schön."},
  {"swedish":"museum","german":"Museum","example":"Vi besöker museet på söndag.","exampleTranslation":"Wir besuchen das Museum am Sonntag."},
  {"swedish":"bio","german":"Kino","example":"Vi går på bio ikväll.","exampleTranslation":"Wir gehen heute Abend ins Kino."},
  {"swedish":"post","german":"Post","example":"Jag skickar brevet på posten.","exampleTranslation":"Ich schicke den Brief auf der Post."},
  {"swedish":"bank","german":"Bank","example":"Jag tar ut pengar på banken.","exampleTranslation":"Ich hebe Geld an der Bank ab."},
  {"swedish":"marknad","german":"Markt","example":"Vi handlar på marknaden.","exampleTranslation":"Wir kaufen auf dem Markt ein."},
  {"swedish":"torg","german":"Marktplatz / Platz","example":"Det finns ett torg i centrum.","exampleTranslation":"Es gibt einen Platz im Stadtzentrum."},
  {"swedish":"bro","german":"Brücke","example":"Vi går över bron.","exampleTranslation":"Wir gehen über die Brücke."},
  {"swedish":"centrum","german":"Stadtzentrum / Innenstadt","example":"Affärerna ligger i centrum.","exampleTranslation":"Die Geschäfte liegen in der Innenstadt."},
  {"swedish":"tunnel","german":"Tunnel","example":"Tåget kör genom tunneln.","exampleTranslation":"Der Zug fährt durch den Tunnel."},
  # Family extensions
  {"swedish":"farbror","german":"Onkel (väterlicherseits)","example":"Min farbror bor i Göteborg.","exampleTranslation":"Mein Onkel wohnt in Göteborg."},
  {"swedish":"faster","german":"Tante (väterlicherseits)","example":"Faster bjuder oss på middag.","exampleTranslation":"Tante (väterlicherseits) lädt uns zum Abendessen ein."},
  {"swedish":"morbror","german":"Onkel (mütterlicherseits)","example":"Morbror är en rolig person.","exampleTranslation":"Onkel (mütterlicherseits) ist eine lustige Person."},
  {"swedish":"moster","german":"Tante (mütterlicherseits)","example":"Moster ger oss presenter.","exampleTranslation":"Tante (mütterlicherseits) gibt uns Geschenke."},
  {"swedish":"kusin","german":"Cousin / Cousine","example":"Mina kusiner bor i Stockholm.","exampleTranslation":"Meine Cousins wohnen in Stockholm."},
  {"swedish":"make","german":"Ehemann","example":"Det är hennes make.","exampleTranslation":"Das ist ihr Ehemann."},
  {"swedish":"maka","german":"Ehefrau","example":"Det är hans maka.","exampleTranslation":"Das ist seine Ehefrau."},
  {"swedish":"pojkvän","german":"Freund (romantisch)","example":"Hon har en ny pojkvän.","exampleTranslation":"Sie hat einen neuen Freund."},
  {"swedish":"flickvän","german":"Freundin (romantisch)","example":"Hans flickvän är lärare.","exampleTranslation":"Seine Freundin ist Lehrerin."},
  {"swedish":"barnbarn","german":"Enkel(kind)","example":"Mormor leker med barnbarnen.","exampleTranslation":"Oma spielt mit den Enkeln."},
  # Nature
  {"swedish":"löv","german":"Blatt / Laub","example":"Löven faller på hösten.","exampleTranslation":"Die Blätter fallen im Herbst."},
  {"swedish":"gren","german":"Ast / Zweig","example":"Fågeln sitter på en gren.","exampleTranslation":"Der Vogel sitzt auf einem Ast."},
  {"swedish":"rot","german":"Wurzel","example":"Trädet har djupa rötter.","exampleTranslation":"Der Baum hat tiefe Wurzeln."},
  {"swedish":"frö","german":"Samen / Korn","example":"Vi planterar frön i trädgården.","exampleTranslation":"Wir pflanzen Samen im Garten."},
  {"swedish":"jord","german":"Erde / Boden","example":"Blommorna växer i jordet.","exampleTranslation":"Die Blumen wachsen in der Erde."},
  {"swedish":"sand","german":"Sand","example":"Barnen leker i sanden.","exampleTranslation":"Die Kinder spielen im Sand."},
  {"swedish":"sten","german":"Stein","example":"Jag hittade en vacker sten.","exampleTranslation":"Ich habe einen schönen Stein gefunden."},
  {"swedish":"flod","german":"Fluss","example":"Floden är bred och lång.","exampleTranslation":"Der Fluss ist breit und lang."},
  {"swedish":"äng","german":"Wiese","example":"Korna betar på ängen.","exampleTranslation":"Die Kühe grasen auf der Wiese."},
  {"swedish":"dal","german":"Tal","example":"Byn ligger i dalen.","exampleTranslation":"Das Dorf liegt im Tal."},
  {"swedish":"is","german":"Eis (gefroren)","example":"Det är halt is på vägen.","exampleTranslation":"Es ist glatteis auf der Straße."},
  {"swedish":"frost","german":"Frost","example":"Det är frost på marken.","exampleTranslation":"Es gibt Frost auf dem Boden."},
  {"swedish":"dimma","german":"Nebel","example":"Det är tät dimma i dag.","exampleTranslation":"Es ist dichter Nebel heute."},
  {"swedish":"regnbåge","german":"Regenbogen","example":"Det finns en vacker regnbåge!","exampleTranslation":"Da ist ein schöner Regenbogen!"},
  {"swedish":"himmel","german":"Himmel","example":"Himlen är klar och blå.","exampleTranslation":"Der Himmel ist klar und blau."},
  # School / work
  {"swedish":"elev","german":"Schüler / Schülerin","example":"Det finns trettio elever i klassen.","exampleTranslation":"Es gibt dreißig Schüler in der Klasse."},
  {"swedish":"student","german":"Student / Studentin","example":"Han är student på universitetet.","exampleTranslation":"Er ist Student an der Universität."},
  {"swedish":"klass","german":"Klasse","example":"Vilken klass går du i?","exampleTranslation":"In welcher Klasse bist du?"},
  {"swedish":"prov","german":"Test / Prüfung","example":"Vi har prov i matematik imorgon.","exampleTranslation":"Wir haben morgen eine Mathprüfung."},
  {"swedish":"läxa","german":"Hausaufgabe","example":"Har du gjort läxan?","exampleTranslation":"Hast du die Hausaufgabe gemacht?"},
  {"swedish":"kontor","german":"Büro","example":"Han arbetar på kontoret.","exampleTranslation":"Er arbeitet im Büro."},
  {"swedish":"chef","german":"Chef / Vorgesetzte/r","example":"Min chef är snäll.","exampleTranslation":"Mein Chef ist nett."},
  {"swedish":"kollega","german":"Kollege / Kollegin","example":"Mina kollegor är trevliga.","exampleTranslation":"Meine Kollegen sind nett."},
  {"swedish":"möte","german":"Treffen / Besprechung","example":"Vi har ett möte klockan tio.","exampleTranslation":"Wir haben um zehn Uhr eine Besprechung."},
  {"swedish":"lön","german":"Gehalt / Lohn","example":"Lönen betalas varje månad.","exampleTranslation":"Das Gehalt wird jeden Monat bezahlt."},
  {"swedish":"semester","german":"Urlaub / Ferien","example":"Vi reser på semester till Italien.","exampleTranslation":"Wir fahren in den Urlaub nach Italien."},
  {"swedish":"papper","german":"Papier","example":"Jag behöver ett papper.","exampleTranslation":"Ich brauche ein Stück Papier."},
  {"swedish":"suddgummi","german":"Radiergummi","example":"Kan jag låna ditt suddgummi?","exampleTranslation":"Kann ich deinen Radiergummi ausleihen?"},
  {"swedish":"lektion","german":"Unterrichtsstunde","example":"Svenska lektionen är kul.","exampleTranslation":"Die Schwedischstunde macht Spaß."},
  {"swedish":"universitet","german":"Universität","example":"Hon studerar på universitetet.","exampleTranslation":"Sie studiert an der Universität."},
  # Health
  {"swedish":"huvudvärk","german":"Kopfschmerzen","example":"Jag har huvudvärk idag.","exampleTranslation":"Ich habe heute Kopfschmerzen."},
  {"swedish":"feber","german":"Fieber","example":"Han har hög feber.","exampleTranslation":"Er hat hohes Fieber."},
  {"swedish":"hosta","german":"Husten","example":"Jag har hostat hela natten.","exampleTranslation":"Ich habe die ganze Nacht gehustet."},
  {"swedish":"förkylning","german":"Erkältung","example":"Jag har en svår förkylning.","exampleTranslation":"Ich habe eine schlimme Erkältung."},
  {"swedish":"medicin","german":"Medizin / Medikament","example":"Ta din medicin!","exampleTranslation":"Nimm deine Medizin!"},
  {"swedish":"plåster","german":"Pflaster","example":"Jag behöver ett plåster.","exampleTranslation":"Ich brauche ein Pflaster."},
  {"swedish":"smärta","german":"Schmerz","example":"Smärtan är stark.","exampleTranslation":"Der Schmerz ist stark."},
  {"swedish":"allergi","german":"Allergie","example":"Jag har pollenallergi.","exampleTranslation":"Ich habe Pollenallergie."},
  {"swedish":"tandläkare","german":"Zahnarzt / Zahnärztin","example":"Jag ska gå till tandläkaren.","exampleTranslation":"Ich gehe zum Zahnarzt."},
  {"swedish":"sjuksköterska","german":"Krankenschwester / Krankenpfleger","example":"Sjuksköterskan tar blodprov.","exampleTranslation":"Die Krankenschwester nimmt Blut ab."},
  # Sports / hobbies
  {"swedish":"sport","german":"Sport","example":"Jag gillar att hålla på med sport.","exampleTranslation":"Ich mag Sport treiben."},
  {"swedish":"fotboll","german":"Fußball","example":"Vi spelar fotboll på söndagar.","exampleTranslation":"Wir spielen sonntags Fußball."},
  {"swedish":"hockey","german":"Eishockey","example":"Hockey är populärt i Sverige.","exampleTranslation":"Eishockey ist in Schweden beliebt."},
  {"swedish":"tennis","german":"Tennis","example":"De spelar tennis på somrarna.","exampleTranslation":"Sie spielen im Sommer Tennis."},
  {"swedish":"simning","german":"Schwimmen","example":"Simning är bra motion.","exampleTranslation":"Schwimmen ist gute Bewegung."},
  {"swedish":"löpning","german":"Laufen / Joggen","example":"Jag tränar löpning tre gånger i veckan.","exampleTranslation":"Ich trainiere dreimal pro Woche Laufen."},
  {"swedish":"musik","german":"Musik","example":"Jag lyssnar på musik varje dag.","exampleTranslation":"Ich höre jeden Tag Musik."},
  {"swedish":"gitarr","german":"Gitarre","example":"Han spelar gitarr i ett band.","exampleTranslation":"Er spielt Gitarre in einer Band."},
  {"swedish":"piano","german":"Klavier","example":"Hon kan spela piano.","exampleTranslation":"Sie kann Klavier spielen."},
  {"swedish":"dans","german":"Tanz / Tanzen","example":"Dans är roligt och nyttigt.","exampleTranslation":"Tanzen macht Spaß und ist gesund."},
  {"swedish":"film","german":"Film","example":"Vi ser en bra film ikväll.","exampleTranslation":"Wir sehen heute Abend einen guten Film."},
  {"swedish":"spel","german":"Spiel","example":"Vi spelar ett spel.","exampleTranslation":"Wir spielen ein Spiel."},
  {"swedish":"hobby","german":"Hobby","example":"Min hobby är att fotografera.","exampleTranslation":"Mein Hobby ist Fotografieren."},
  {"swedish":"träning","german":"Training / Sport treiben","example":"Jag går på träning tre gånger i veckan.","exampleTranslation":"Ich gehe dreimal pro Woche zum Training."},
  {"swedish":"yoga","german":"Yoga","example":"Yoga är bra för kroppen och sinnet.","exampleTranslation":"Yoga ist gut für Körper und Geist."},
  # Technology
  {"swedish":"internet","german":"Internet","example":"Jag söker information på internet.","exampleTranslation":"Ich suche Informationen im Internet."},
  {"swedish":"app","german":"App","example":"Jag laddar ner en ny app.","exampleTranslation":"Ich lade eine neue App herunter."},
  {"swedish":"mejl","german":"E-Mail","example":"Skicka mig ett mejl!","exampleTranslation":"Schick mir eine E-Mail!"},
  {"swedish":"meddelande","german":"Nachricht","example":"Jag fick ett meddelande.","exampleTranslation":"Ich habe eine Nachricht bekommen."},
  {"swedish":"hemsida","german":"Webseite / Homepage","example":"Titta på vår hemsida.","exampleTranslation":"Schau dir unsere Webseite an."},
  {"swedish":"kamera","german":"Kamera","example":"Jag tar bilder med kameran.","exampleTranslation":"Ich mache Bilder mit der Kamera."},
  {"swedish":"radio","german":"Radio","example":"Vi hör på radio på morgonen.","exampleTranslation":"Wir hören morgens Radio."},
  {"swedish":"tidning","german":"Zeitung","example":"Jag läser tidningen varje dag.","exampleTranslation":"Ich lese jeden Tag die Zeitung."},
  {"swedish":"program","german":"Programm","example":"Vilket program ser du på?","exampleTranslation":"Welches Programm schaust du?"},
  {"swedish":"skärm","german":"Bildschirm","example":"Skärmen är för liten.","exampleTranslation":"Der Bildschirm ist zu klein."},
  # Function words / adverbs
  {"swedish":"något","german":"etwas","example":"Vill du ha något att äta?","exampleTranslation":"Möchtest du etwas essen?"},
  {"swedish":"alla","german":"alle","example":"Alla är välkomna!","exampleTranslation":"Alle sind willkommen!"},
  {"swedish":"ingen","german":"niemand / kein","example":"Ingen kom till festen.","exampleTranslation":"Niemand kam zur Party."},
  {"swedish":"varje","german":"jede/r/s","example":"Jag tränar varje dag.","exampleTranslation":"Ich trainiere jeden Tag."},
  {"swedish":"några","german":"einige / ein paar","example":"Jag har några frågor.","exampleTranslation":"Ich habe ein paar Fragen."},
  {"swedish":"annan","german":"andere/r/s","example":"Jag vill ha ett annat rum.","exampleTranslation":"Ich möchte ein anderes Zimmer."},
  {"swedish":"samma","german":"gleiche/r/s / derselbe","example":"Vi bor på samma gata.","exampleTranslation":"Wir wohnen in derselben Straße."},
  {"swedish":"igen","german":"wieder / nochmal","example":"Kan du säga det igen?","exampleTranslation":"Kannst du das nochmal sagen?"},
  {"swedish":"tillbaka","german":"zurück","example":"Jag kommer tillbaka imorgon.","exampleTranslation":"Ich komme morgen zurück."},
  {"swedish":"ut","german":"raus / hinaus","example":"Gå ut och lek!","exampleTranslation":"Geh raus und spiel!"},
  {"swedish":"in","german":"rein / hinein","example":"Kom in och sitt ner!","exampleTranslation":"Komm rein und setz dich!"},
  {"swedish":"dit","german":"dorthin","example":"Vi åker dit imorgon.","exampleTranslation":"Wir fahren morgen dorthin."},
  {"swedish":"hit","german":"hierher","example":"Kom hit!","exampleTranslation":"Komm hierher!"},
  {"swedish":"ungefär","german":"ungefähr","example":"Det tar ungefär en timme.","exampleTranslation":"Es dauert ungefähr eine Stunde."},
  {"swedish":"nästan","german":"fast / beinahe","example":"Jag är nästan klar.","exampleTranslation":"Ich bin fast fertig."},
  {"swedish":"mer","german":"mehr","example":"Kan jag få mer vatten?","exampleTranslation":"Kann ich mehr Wasser haben?"},
  {"swedish":"mest","german":"am meisten / meist","example":"Hon gillar choklad mest.","exampleTranslation":"Sie mag Schokolade am meisten."},
  {"swedish":"mindre","german":"weniger","example":"Ät mindre socker!","exampleTranslation":"Iss weniger Zucker!"},
  {"swedish":"minst","german":"am wenigsten / mindestens","example":"Jag sover minst sju timmar.","exampleTranslation":"Ich schlafe mindestens sieben Stunden."},
  {"swedish":"precis","german":"genau / gerade","example":"Det är precis vad jag vill ha.","exampleTranslation":"Das ist genau das, was ich möchte."},
  # Social expressions
  {"swedish":"lycka till","german":"viel Erfolg / viel Glück","example":"Lycka till på provet!","exampleTranslation":"Viel Erfolg bei der Prüfung!"},
  {"swedish":"grattis","german":"Glückwunsch / herzlichen Glückwunsch","example":"Grattis på födelsedag!","exampleTranslation":"Herzlichen Glückwunsch zum Geburtstag!"},
  {"swedish":"ursäkta","german":"Entschuldigung (um Aufmerksamkeit bitten)","example":"Ursäkta, var är toaletten?","exampleTranslation":"Entschuldigung, wo ist die Toilette?"},
  {"swedish":"hallå","german":"Hallo / Hey","example":"Hallå! Är det någon hemma?","exampleTranslation":"Hallo! Ist jemand zu Hause?"},
  {"swedish":"ha det bra","german":"pass auf dich auf / mach's gut","example":"Hej då, ha det bra!","exampleTranslation":"Tschüss, mach's gut!"},
  {"swedish":"självklart","german":"natürlich / selbstverständlich","example":"Självklart hjälper jag dig!","exampleTranslation":"Natürlich helfe ich dir!"},
  {"swedish":"absolut","german":"absolut / auf jeden Fall","example":"Absolut, det är en bra idé!","exampleTranslation":"Absolut, das ist eine gute Idee!"},
  {"swedish":"inga problem","german":"kein Problem","example":"Inga problem, jag fixar det.","exampleTranslation":"Kein Problem, ich erledige das."},
  {"swedish":"okej","german":"okay","example":"Okej, vi ses imorgon!","exampleTranslation":"Okay, wir sehen uns morgen!"},
  {"swedish":"trevlig","german":"nett / angenehm","example":"Ha en trevlig dag!","exampleTranslation":"Hab einen angenehmen Tag!"},
  # Sweden / culture
  {"swedish":"Sverige","german":"Schweden","example":"Sverige är ett nordiskt land.","exampleTranslation":"Schweden ist ein nordisches Land."},
  {"swedish":"Göteborg","german":"Göteborg","example":"Göteborg är Sveriges andra stad.","exampleTranslation":"Göteborg ist Schwedens zweitgrößte Stadt."},
  {"swedish":"Malmö","german":"Malmö","example":"Malmö ligger i södra Sverige.","exampleTranslation":"Malmö liegt im Süden Schwedens."},
  {"swedish":"svenska","german":"Schwedisch (Sprache)","example":"Jag lär mig svenska.","exampleTranslation":"Ich lerne Schwedisch."},
  {"swedish":"fika","german":"Fika (schwedische Kaffeepause)","example":"Vi tar en fika klockan tre.","exampleTranslation":"Wir machen um drei Uhr Fika."},
  {"swedish":"jul","german":"Weihnachten","example":"Vi firar jul med familjen.","exampleTranslation":"Wir feiern Weihnachten mit der Familie."},
  {"swedish":"nyår","german":"Neujahr","example":"Gott nytt år!","exampleTranslation":"Frohes neues Jahr!"},
  {"swedish":"midsommar","german":"Mittsommer","example":"Midsommar firas i juni.","exampleTranslation":"Mittsommer wird im Juni gefeiert."},
  {"swedish":"krona","german":"Krone (schwedische Währung)","example":"Det kostar hundra kronor.","exampleTranslation":"Es kostet hundert Kronen."},
  {"swedish":"flagga","german":"Fahne / Flagge","example":"Den svenska flaggan är blå och gul.","exampleTranslation":"Die schwedische Flagge ist blau und gelb."},
  # More animals
  {"swedish":"björn","german":"Bär","example":"Det finns björnar i Sverige.","exampleTranslation":"Es gibt Bären in Schweden."},
  {"swedish":"älg","german":"Elch","example":"Älgen är ett stort djur.","exampleTranslation":"Der Elch ist ein großes Tier."},
  {"swedish":"räv","german":"Fuchs","example":"Räven springer snabbt.","exampleTranslation":"Der Fuchs läuft schnell."},
  {"swedish":"orm","german":"Schlange","example":"Jag är rädd för ormar.","exampleTranslation":"Ich habe Angst vor Schlangen."},
  {"swedish":"lejon","german":"Löwe","example":"Lejonet är djungelns kung.","exampleTranslation":"Der Löwe ist der König des Dschungels."},
  {"swedish":"elefant","german":"Elefant","example":"Elefanten är det största djuret på land.","exampleTranslation":"Der Elefant ist das größte Landtier."},
  {"swedish":"apa","german":"Affe","example":"Apan klättrar i trädet.","exampleTranslation":"Der Affe klettert im Baum."},
  {"swedish":"zebra","german":"Zebra","example":"Zebror lever i Afrika.","exampleTranslation":"Zebras leben in Afrika."},
  {"swedish":"giraff","german":"Giraffe","example":"Giraffen har lång hals.","exampleTranslation":"Die Giraffe hat einen langen Hals."},
  {"swedish":"svan","german":"Schwan","example":"Svanen simmar på sjön.","exampleTranslation":"Der Schwan schwimmt auf dem See."},
  # More weather
  {"swedish":"temperatur","german":"Temperatur","example":"Temperaturen är minus tio grader.","exampleTranslation":"Die Temperatur ist minus zehn Grad."},
  {"swedish":"grad","german":"Grad","example":"Det är tjugo grader varmt.","exampleTranslation":"Es ist zwanzig Grad warm."},
  {"swedish":"storm","german":"Sturm","example":"Det är storm ute idag.","exampleTranslation":"Draußen ist heute ein Sturm."},
  {"swedish":"ljus","german":"Licht","example":"Tänd ljuset, det är mörkt.","exampleTranslation":"Mach das Licht an, es ist dunkel."},
  {"swedish":"mörker","german":"Dunkelheit / Dunkel","example":"Jag är rädd för mörkret.","exampleTranslation":"Ich habe Angst vor der Dunkelheit."},
  {"swedish":"hagel","german":"Hagel","example":"Det faller hagel utanför.","exampleTranslation":"Draußen fällt Hagel."},
  {"swedish":"solsken","german":"Sonnenschein","example":"Vi njuter av solskenet.","exampleTranslation":"Wir genießen den Sonnenschein."},
  {"swedish":"paraply","german":"Regenschirm","example":"Ta paraplyet, det regnar!","exampleTranslation":"Nimm den Regenschirm, es regnet!"},
  {"swedish":"termometer","german":"Thermometer","example":"Termometern visar trettio grader.","exampleTranslation":"Das Thermometer zeigt dreißig Grad."},
  {"swedish":"blåsig","german":"windig","example":"Det är kallt och blåsigt.","exampleTranslation":"Es ist kalt und windig."},
  # Body actions
  {"swedish":"att andas","german":"atmen","example":"Andas djupt och lugnt.","exampleTranslation":"Atme tief und ruhig."},
  {"swedish":"att röra sig","german":"sich bewegen","example":"Det är viktigt att röra sig varje dag.","exampleTranslation":"Es ist wichtig, sich jeden Tag zu bewegen."},
  {"swedish":"att vila","german":"sich ausruhen","example":"Jag behöver vila lite.","exampleTranslation":"Ich muss mich etwas ausruhen."},
  {"swedish":"att träna","german":"trainieren / Sport treiben","example":"Jag tränar på gymmet varje måndag.","exampleTranslation":"Ich trainiere jeden Montag im Fitnessstudio."},
  {"swedish":"att hosta","german":"husten","example":"Jag hostar eftersom jag är sjuk.","exampleTranslation":"Ich huste, weil ich krank bin."},
  {"swedish":"att nysa","german":"niesen","example":"Hon nyser hela tiden.","exampleTranslation":"Sie niest die ganze Zeit."},
  {"swedish":"att blöda","german":"bluten","example":"Såret blöder.","exampleTranslation":"Die Wunde blutet."},
  {"swedish":"att svimma","german":"ohnmächtig werden","example":"Han svimmade av värmen.","exampleTranslation":"Er wurde vor Hitze ohnmächtig."},
  {"swedish":"att ha ont","german":"Schmerzen haben / wehtun","example":"Jag har ont i halsen.","exampleTranslation":"Mein Hals tut weh."},
  {"swedish":"att växa","german":"wachsen","example":"Barnet växer snabbt.","exampleTranslation":"Das Kind wächst schnell."},
  # Emotions
  {"swedish":"nöjd","german":"zufrieden","example":"Jag är nöjd med maten.","exampleTranslation":"Ich bin mit dem Essen zufrieden."},
  {"swedish":"besviken","german":"enttäuscht","example":"Han är besviken på resultatet.","exampleTranslation":"Er ist vom Ergebnis enttäuscht."},
  {"swedish":"stolt","german":"stolz","example":"Jag är stolt över dig!","exampleTranslation":"Ich bin stolz auf dich!"},
  {"swedish":"skamsen","german":"beschämt","example":"Hon kände sig skamsen.","exampleTranslation":"Sie fühlte sich beschämt."},
  {"swedish":"blyg","german":"schüchtern","example":"Han är lite blyg med nya människor.","exampleTranslation":"Er ist etwas schüchtern mit neuen Menschen."},
  {"swedish":"modig","german":"mutig","example":"Brandmannen är modig.","exampleTranslation":"Der Feuerwehrmann ist mutig."},
  {"swedish":"ivrig","german":"eifrig / begeistert","example":"Barnet är ivrigt att leka.","exampleTranslation":"Das Kind ist begeistert zu spielen."},
  {"swedish":"lat","german":"faul","example":"Han är lat och vill inte jobba.","exampleTranslation":"Er ist faul und will nicht arbeiten."},
  {"swedish":"flitig","german":"fleißig","example":"Hon är flitig och arbetar hårt.","exampleTranslation":"Sie ist fleißig und arbeitet hart."},
  {"swedish":"otålig","german":"ungeduldig","example":"Jag är otålig, kom nu!","exampleTranslation":"Ich bin ungeduldig, komm jetzt!"},
  # Directions
  {"swedish":"rakt fram","german":"geradeaus","example":"Gå rakt fram, sedan sväng höger.","exampleTranslation":"Geh geradeaus, dann biege rechts ab."},
  {"swedish":"runt","german":"rund / um ... herum","example":"Vi gick runt sjön.","exampleTranslation":"Wir gingen um den See herum."},
  {"swedish":"utanför","german":"draußen / außerhalb","example":"Barnen leker utanför.","exampleTranslation":"Die Kinder spielen draußen."},
  {"swedish":"innanför","german":"drinnen / innerhalb","example":"Kom innanför!","exampleTranslation":"Komm rein!"},
  {"swedish":"ovanför","german":"darüber / oberhalb","example":"Lampan hänger ovanför bordet.","exampleTranslation":"Die Lampe hängt über dem Tisch."},
  {"swedish":"nedanför","german":"darunter / unterhalb","example":"Katterna sover nedanför sängen.","exampleTranslation":"Die Katzen schlafen unter dem Bett."},
  {"swedish":"längs","german":"entlang","example":"Vi gick längs stranden.","exampleTranslation":"Wir gingen am Strand entlang."},
  {"swedish":"mot","german":"in Richtung / gegen","example":"Vi går mot stationen.","exampleTranslation":"Wir gehen in Richtung Bahnhof."},
  {"swedish":"förbi","german":"vorbei / an ... vorbei","example":"Bussen kör förbi skolan.","exampleTranslation":"Der Bus fährt an der Schule vorbei."},
  {"swedish":"riktning","german":"Richtung","example":"Vi går i fel riktning.","exampleTranslation":"Wir gehen in die falsche Richtung."},
  # Shopping
  {"swedish":"att handla","german":"einkaufen","example":"Vi handlar mat på fredagen.","exampleTranslation":"Wir kaufen freitags Lebensmittel ein."},
  {"swedish":"kassan","german":"Kasse","example":"Stå i kö vid kassan.","exampleTranslation":"Steh an der Kasse an."},
  {"swedish":"kvitto","german":"Quittung / Kassenbon","example":"Kan jag få ett kvitto?","exampleTranslation":"Kann ich eine Quittung bekommen?"},
  {"swedish":"rabatt","german":"Rabatt / Ermäßigung","example":"Jag fick tjugo procent rabatt.","exampleTranslation":"Ich bekam zwanzig Prozent Rabatt."},
  {"swedish":"rea","german":"Ausverkauf / Sale","example":"Det är rea på jackor idag.","exampleTranslation":"Heute sind Jacken im Ausverkauf."},
  {"swedish":"erbjudande","german":"Angebot","example":"Det finns ett bra erbjudande.","exampleTranslation":"Es gibt ein gutes Angebot."},
  {"swedish":"korg","german":"Korb / Einkaufskorb","example":"Jag bär korgen med äpplen.","exampleTranslation":"Ich trage den Korb mit Äpfeln."},
  {"swedish":"påse","german":"Tüte / Beutel","example":"Kan jag få en påse?","exampleTranslation":"Kann ich eine Tüte haben?"},
  {"swedish":"klädaffär","german":"Bekleidungsgeschäft","example":"Det finns en klädaffär på torget.","exampleTranslation":"Es gibt ein Bekleidungsgeschäft auf dem Marktplatz."},
  {"swedish":"mataffär","german":"Lebensmittelgeschäft / Supermarkt","example":"Jag köper mat i mataffären.","exampleTranslation":"Ich kaufe Lebensmittel im Supermarkt."},
  # At the restaurant
  {"swedish":"meny","german":"Speisekarte / Menü","example":"Kan jag få se menyn?","exampleTranslation":"Kann ich die Speisekarte sehen?"},
  {"swedish":"att beställa","german":"bestellen","example":"Jag vill beställa mat.","exampleTranslation":"Ich möchte Essen bestellen."},
  {"swedish":"räkning","german":"Rechnung","example":"Kan jag få räkningen?","exampleTranslation":"Kann ich die Rechnung haben?"},
  {"swedish":"dryck","german":"Getränk","example":"Vilken dryck vill du ha?","exampleTranslation":"Welches Getränk möchtest du?"},
  {"swedish":"förrätt","german":"Vorspeise","example":"Jag väljer soppan som förrätt.","exampleTranslation":"Ich wähle die Suppe als Vorspeise."},
  {"swedish":"huvudrätt","german":"Hauptgericht","example":"Vad tar du som huvudrätt?","exampleTranslation":"Was nimmst du als Hauptgericht?"},
  {"swedish":"dessert","german":"Dessert / Nachspeise","example":"Vill du ha dessert?","exampleTranslation":"Möchtest du ein Dessert?"},
  {"swedish":"servitör","german":"Kellner","example":"Servitören kommer snart.","exampleTranslation":"Der Kellner kommt gleich."},
  {"swedish":"servitris","german":"Kellnerin","example":"Servitrisen är vänlig.","exampleTranslation":"Die Kellnerin ist freundlich."},
  {"swedish":"dricks","german":"Trinkgeld","example":"Jag lämnar dricks på bordet.","exampleTranslation":"Ich lasse Trinkgeld auf dem Tisch."},
  # Travel
  {"swedish":"pass","german":"Reisepass","example":"Glöm inte passet!","exampleTranslation":"Vergiss den Reisepass nicht!"},
  {"swedish":"biljett","german":"Fahrkarte / Ticket","example":"Jag köper en biljett till Stockholm.","exampleTranslation":"Ich kaufe eine Fahrkarte nach Stockholm."},
  {"swedish":"bagage","german":"Gepäck","example":"Mitt bagage är för tungt.","exampleTranslation":"Mein Gepäck ist zu schwer."},
  {"swedish":"hotellrum","german":"Hotelzimmer","example":"Hotellrummet är bekvämt.","exampleTranslation":"Das Hotelzimmer ist bequem."},
  {"swedish":"karta","german":"Karte / Landkarte","example":"Vi tittar på kartan.","exampleTranslation":"Wir schauen auf die Karte."},
  {"swedish":"turist","german":"Tourist / Touristin","example":"Turister besöker Stockholm varje år.","exampleTranslation":"Touristen besuchen Stockholm jedes Jahr."},
  {"swedish":"utland","german":"Ausland","example":"Jag har aldrig rest utomlands.","exampleTranslation":"Ich bin noch nie ins Ausland gereist."},
  {"swedish":"resväska","german":"Koffer","example":"Jag packar resväskan.","exampleTranslation":"Ich packe den Koffer."},
  {"swedish":"incheckning","german":"Check-in / Einchecken","example":"Incheckningen börjar klockan tio.","exampleTranslation":"Der Check-in beginnt um zehn Uhr."},
  {"swedish":"avresa","german":"Abfahrt / Abreise","example":"Avresan är klockan åtta på morgonen.","exampleTranslation":"Die Abreise ist um acht Uhr morgens."},
  # Communication
  {"swedish":"brev","german":"Brief","example":"Jag skriver ett brev till mormor.","exampleTranslation":"Ich schreibe einen Brief an Oma."},
  {"swedish":"paket","german":"Paket","example":"Paketet kom idag.","exampleTranslation":"Das Paket kam heute."},
  {"swedish":"adress","german":"Adresse","example":"Vilken adress bor du på?","exampleTranslation":"An welcher Adresse wohnst du?"},
  {"swedish":"postnummer","german":"Postleitzahl","example":"Vad är ditt postnummer?","exampleTranslation":"Was ist deine Postleitzahl?"},
  {"swedish":"namn","german":"Name","example":"Vad är ditt namn?","exampleTranslation":"Was ist dein Name?"},
  {"swedish":"efternamn","german":"Nachname","example":"Vad är ditt efternamn?","exampleTranslation":"Was ist dein Nachname?"},
  {"swedish":"förnamn","german":"Vorname","example":"Mitt förnamn är Erik.","exampleTranslation":"Mein Vorname ist Erik."},
  {"swedish":"underskrift","german":"Unterschrift","example":"Skriv din underskrift här.","exampleTranslation":"Schreib hier deine Unterschrift."},
  {"swedish":"formulär","german":"Formular","example":"Fyll i formuläret, tack.","exampleTranslation":"Füll das Formular aus, bitte."},
  {"swedish":"nummer","german":"Nummer","example":"Vad är ditt telefonnummer?","exampleTranslation":"Was ist deine Telefonnummer?"},
  # Numbers / math
  {"swedish":"plus","german":"plus","example":"Tre plus tre är sex.","exampleTranslation":"Drei plus drei ist sechs."},
  {"swedish":"minus","german":"minus","example":"Tio minus fyra är sex.","exampleTranslation":"Zehn minus vier ist sechs."},
  {"swedish":"gånger","german":"mal (Multiplikation)","example":"Tre gånger tre är nio.","exampleTranslation":"Drei mal drei ist neun."},
  {"swedish":"delat med","german":"geteilt durch","example":"Tio delat med två är fem.","exampleTranslation":"Zehn geteilt durch zwei ist fünf."},
  {"swedish":"hälften","german":"Hälfte","example":"Jag vill ha hälften av kakan.","exampleTranslation":"Ich möchte die Hälfte des Kuchens."},
  {"swedish":"dubbelt","german":"doppelt","example":"Det kostar dubbelt så mycket.","exampleTranslation":"Es kostet doppelt so viel."},
  {"swedish":"tredje","german":"dritte/r/s","example":"Det är tredje gången.","exampleTranslation":"Das ist das dritte Mal."},
  {"swedish":"första","german":"erste/r/s","example":"Jag är den första i kön.","exampleTranslation":"Ich bin der Erste in der Schlange."},
  {"swedish":"sista","german":"letzte/r/s","example":"Det är sista tåget ikväll.","exampleTranslation":"Das ist der letzte Zug heute Abend."},
  {"swedish":"andra","german":"zweite/r/s","example":"Det är andra gången jag besöker Sverige.","exampleTranslation":"Das ist das zweite Mal, dass ich Schweden besuche."},
  # Conjunctions
  {"swedish":"fast","german":"obwohl / trotzdem","example":"Hon gick ut fast det regnade.","exampleTranslation":"Sie ging raus, obwohl es regnete."},
  {"swedish":"eftersom","german":"weil / da","example":"Jag stannar hemma eftersom jag är sjuk.","exampleTranslation":"Ich bleibe zu Hause, weil ich krank bin."},
  {"swedish":"så att","german":"damit / sodass","example":"Tala högt så att alla hör.","exampleTranslation":"Sprich laut, damit alle hören."},
  {"swedish":"utan","german":"ohne","example":"Jag kan inte leva utan dig.","exampleTranslation":"Ich kann nicht ohne dich leben."},
  {"swedish":"utom","german":"außer","example":"Alla kom utom Erik.","exampleTranslation":"Alle kamen außer Erik."},
  {"swedish":"istället","german":"stattdessen","example":"Ta te istället för kaffe.","exampleTranslation":"Nimm Tee stattdessen Kaffee."},
  {"swedish":"annars","german":"sonst / andernfalls","example":"Skynda dig, annars missar du bussen.","exampleTranslation":"Beeil dich, sonst verpasst du den Bus."},
  {"swedish":"antingen","german":"entweder","example":"Antingen äter vi hemma eller ute.","exampleTranslation":"Entweder essen wir zu Hause oder auswärts."},
  {"swedish":"varken","german":"weder","example":"Jag vill varken äta eller dricka.","exampleTranslation":"Ich will weder essen noch trinken."},
  {"swedish":"trots att","german":"obwohl / trotz","example":"Han kom trots att han var trött.","exampleTranslation":"Er kam, obwohl er müde war."},
  # Occupations
  {"swedish":"kock","german":"Koch / Köchin","example":"Kocken lagar fantastisk mat.","exampleTranslation":"Der Koch kocht fantastisches Essen."},
  {"swedish":"ingenjör","german":"Ingenieur / Ingenieurin","example":"Min bror är ingenjör.","exampleTranslation":"Mein Bruder ist Ingenieur."},
  {"swedish":"advokat","german":"Anwalt / Anwältin","example":"Hon är advokat.","exampleTranslation":"Sie ist Anwältin."},
  {"swedish":"journalist","german":"Journalist / Journalistin","example":"Journalisten skriver artiklar.","exampleTranslation":"Der Journalist schreibt Artikel."},
  {"swedish":"säljare","german":"Verkäufer / Verkäuferin","example":"Säljaren hjälper kunden.","exampleTranslation":"Der Verkäufer hilft dem Kunden."},
  {"swedish":"elektriker","german":"Elektriker / Elektrikerin","example":"Vi behöver en elektriker.","exampleTranslation":"Wir brauchen einen Elektriker."},
  {"swedish":"snickare","german":"Tischler / Zimmermann","example":"Snickaren bygger möbler.","exampleTranslation":"Der Tischler baut Möbel."},
  {"swedish":"frisör","german":"Friseur / Friseurin","example":"Jag ska klippa mig hos frisören.","exampleTranslation":"Ich lasse mir beim Friseur die Haare schneiden."},
  {"swedish":"konstnär","german":"Künstler / Künstlerin","example":"Konstnären målar vackra tavlor.","exampleTranslation":"Der Künstler malt schöne Bilder."},
  {"swedish":"musiker","german":"Musiker / Musikerin","example":"Musikern spelar på konserten.","exampleTranslation":"Der Musiker spielt im Konzert."},
  # More transport
  {"swedish":"tunnelbana","german":"U-Bahn","example":"Vi tar tunnelbanan in till stan.","exampleTranslation":"Wir nehmen die U-Bahn in die Stadt."},
  {"swedish":"spårvagn","german":"Straßenbahn","example":"Spårvagnen stannar här.","exampleTranslation":"Die Straßenbahn hält hier."},
  {"swedish":"taxi","german":"Taxi","example":"Vi tar en taxi till flygplatsen.","exampleTranslation":"Wir nehmen ein Taxi zum Flughafen."},
  {"swedish":"lastbil","german":"Lastwagen / LKW","example":"Lastbilen transporterar varor.","exampleTranslation":"Der Lastwagen transportiert Waren."},
  {"swedish":"motorcykel","german":"Motorrad","example":"Han kör motorcykel på sommaren.","exampleTranslation":"Er fährt im Sommer Motorrad."},
  {"swedish":"moped","german":"Moped / Mofa","example":"Ungdomarna kör moped.","exampleTranslation":"Die Jugendlichen fahren Moped."},
  {"swedish":"helikopter","german":"Hubschrauber","example":"Helikoptern flyger lågt.","exampleTranslation":"Der Hubschrauber fliegt niedrig."},
  {"swedish":"färja","german":"Fähre","example":"Vi tar färjan till Danmark.","exampleTranslation":"Wir nehmen die Fähre nach Dänemark."},
  {"swedish":"hållplats","german":"Haltestelle","example":"Nästa hållplats är Stortorget.","exampleTranslation":"Die nächste Haltestelle ist Stortorget."},
  {"swedish":"ankomst","german":"Ankunft","example":"Ankomsten är klockan tolv.","exampleTranslation":"Die Ankunft ist um zwölf Uhr."},
  # School items
  {"swedish":"tavla","german":"Tafel / Whiteboard","example":"Läraren skriver på tavlan.","exampleTranslation":"Der Lehrer schreibt an die Tafel."},
  {"swedish":"krita","german":"Kreide","example":"Kan jag få en bit krita?","exampleTranslation":"Kann ich ein Stück Kreide haben?"},
  {"swedish":"linjal","german":"Lineal","example":"Jag drar en rak linje med linjalen.","exampleTranslation":"Ich ziehe eine gerade Linie mit dem Lineal."},
  {"swedish":"sax","german":"Schere","example":"Klipp med saxen!","exampleTranslation":"Schneide mit der Schere!"},
  {"swedish":"lim","german":"Kleber / Klebstoff","example":"Använd lim för att sätta ihop bitarna.","exampleTranslation":"Benutze Kleber, um die Teile zusammenzusetzen."},
  {"swedish":"ryggsäck","german":"Rucksack","example":"Jag bär böckerna i ryggsäcken.","exampleTranslation":"Ich trage die Bücher im Rucksack."},
  {"swedish":"pennfodral","german":"Federmäppchen","example":"Min penna är i pennfodralet.","exampleTranslation":"Mein Stift ist im Federmäppchen."},
  {"swedish":"anteckningsbok","german":"Notizbuch","example":"Jag skriver i anteckningsboken.","exampleTranslation":"Ich schreibe ins Notizbuch."},
  {"swedish":"klassrum","german":"Klassenzimmer","example":"Det finns tjugo elever i klassrummet.","exampleTranslation":"Es gibt zwanzig Schüler im Klassenzimmer."},
  {"swedish":"korridor","german":"Flur / Korridor","example":"Eleverna springer i korridoren.","exampleTranslation":"Die Schüler rennen im Flur."},
  # Personality
  {"swedish":"generös","german":"großzügig","example":"Han är mycket generös.","exampleTranslation":"Er ist sehr großzügig."},
  {"swedish":"självisk","german":"selbstsüchtig / egoistisch","example":"Det är själviskt att inte dela.","exampleTranslation":"Es ist egoistisch, nicht zu teilen."},
  {"swedish":"ärlig","german":"ehrlich","example":"Det är viktigt att vara ärlig.","exampleTranslation":"Es ist wichtig, ehrlich zu sein."},
  {"swedish":"humoristisk","german":"humorvoll","example":"Han är väldigt humoristisk.","exampleTranslation":"Er ist sehr humorvoll."},
  {"swedish":"allvarlig","german":"ernst / ernsthaft","example":"Hon är alltid allvarlig på jobbet.","exampleTranslation":"Sie ist auf der Arbeit immer ernst."},
  {"swedish":"öppen","german":"offen","example":"Han är öppen och social.","exampleTranslation":"Er ist offen und gesellig."},
  {"swedish":"kreativ","german":"kreativ","example":"Barnet är kreativt och fantasirikt.","exampleTranslation":"Das Kind ist kreativ und fantasievoll."},
  {"swedish":"smart","german":"klug / schlau","example":"Hon är smart och löser problem snabbt.","exampleTranslation":"Sie ist klug und löst Probleme schnell."},
  {"swedish":"tålamodig","german":"geduldig","example":"En bra lärare är tålamodig.","exampleTranslation":"Ein guter Lehrer ist geduldig."},
  {"swedish":"ambitiös","german":"ehrgeizig / ambitioniert","example":"Han är ambitiös och jobbar hårt.","exampleTranslation":"Er ist ehrgeizig und arbeitet hart."},
  # Time expressions
  {"swedish":"förra veckan","german":"letzte Woche","example":"Förra veckan var vi i Berlin.","exampleTranslation":"Letzte Woche waren wir in Berlin."},
  {"swedish":"nästa vecka","german":"nächste Woche","example":"Vi reser nästa vecka.","exampleTranslation":"Wir reisen nächste Woche."},
  {"swedish":"i morse","german":"heute Morgen","example":"Jag ringde dig i morse.","exampleTranslation":"Ich habe dich heute Morgen angerufen."},
  {"swedish":"i kväll","german":"heute Abend","example":"Vad gör du i kväll?","exampleTranslation":"Was machst du heute Abend?"},
  {"swedish":"i natt","german":"heute Nacht / letzte Nacht","example":"Jag sov dåligt i natt.","exampleTranslation":"Ich habe letzte Nacht schlecht geschlafen."},
  {"swedish":"förra månaden","german":"letzten Monat","example":"Förra månaden var vi i Paris.","exampleTranslation":"Letzten Monat waren wir in Paris."},
  {"swedish":"nästa år","german":"nächstes Jahr","example":"Vi gifter oss nästa år.","exampleTranslation":"Wir heiraten nächstes Jahr."},
  {"swedish":"om en stund","german":"in einem Moment / gleich","example":"Jag kommer om en stund.","exampleTranslation":"Ich komme gleich."},
  {"swedish":"hela dagen","german":"den ganzen Tag","example":"Jag jobbade hela dagen.","exampleTranslation":"Ich habe den ganzen Tag gearbeitet."},
  {"swedish":"varannan dag","german":"jeden zweiten Tag","example":"Jag tränar varannan dag.","exampleTranslation":"Ich trainiere jeden zweiten Tag."},
  # Swedish culture II
  {"swedish":"smörgåsbord","german":"Smörgåsbord (schwed. Büfett)","example":"Vi äter smörgåsbord på jul.","exampleTranslation":"Wir essen Smörgåsbord zu Weihnachten."},
  {"swedish":"kanelbulle","german":"Zimtschnecke","example":"Jag älskar kanelbullar!","exampleTranslation":"Ich liebe Zimtschnecken!"},
  {"swedish":"pannkaka","german":"Pfannkuchen","example":"Vi äter pannkakor på torsdagar.","exampleTranslation":"Wir essen Pfannkuchen donnerstags."},
  {"swedish":"köttbullar","german":"Hackbällchen / Fleischbällchen","example":"Svenska köttbullar är världskända.","exampleTranslation":"Schwedische Hackbällchen sind weltberühmt."},
  {"swedish":"lingon","german":"Preiselbeere","example":"Lingonsylt är gott till köttbullar.","exampleTranslation":"Preiselbeermarmelade schmeckt gut zu Hackbällchen."},
  {"swedish":"surströmming","german":"Surströmming (fermentierter Hering)","example":"Surströmming luktar starkt.","exampleTranslation":"Surströmming riecht stark."},
  {"swedish":"tradition","german":"Tradition","example":"Det är en gammal tradition.","exampleTranslation":"Das ist eine alte Tradition."},
  {"swedish":"högtid","german":"Feiertag / Fest","example":"Jul är en viktig högtid.","exampleTranslation":"Weihnachten ist ein wichtiger Feiertag."},
  {"swedish":"valborg","german":"Walpurgisnacht","example":"Valborg firas den sista april.","exampleTranslation":"Walpurgisnacht wird am letzten April gefeiert."},
  {"swedish":"kräftskiva","german":"Krebsparty (schwed. Tradition)","example":"Vi har kräftskiva i augusti.","exampleTranslation":"Wir feiern die Krebsparty im August."},
  # At the doctor
  {"swedish":"undersökning","german":"Untersuchung","example":"Läkaren gör en undersökning.","exampleTranslation":"Der Arzt macht eine Untersuchung."},
  {"swedish":"recept","german":"Rezept (Arztrezept)","example":"Jag behöver ett recept för medicinen.","exampleTranslation":"Ich brauche ein Rezept für das Medikament."},
  {"swedish":"dos","german":"Dosis","example":"Ta en dos tre gånger om dagen.","exampleTranslation":"Nimm eine Dosis dreimal täglich."},
  {"swedish":"tablett","german":"Tablette","example":"Ta två tabletter med vatten.","exampleTranslation":"Nimm zwei Tabletten mit Wasser."},
  {"swedish":"spruta","german":"Spritze","example":"Jag är rädd för sprutor.","exampleTranslation":"Ich habe Angst vor Spritzen."},
  {"swedish":"blodprov","german":"Bluttest / Blutabnahme","example":"Läkaren tar ett blodprov.","exampleTranslation":"Der Arzt nimmt Blut ab."},
  {"swedish":"väntrummet","german":"Wartezimmer","example":"Vänta i väntrummet.","exampleTranslation":"Warte im Wartezimmer."},
  {"swedish":"tidsbeställning","german":"Termin(buchung)","example":"Jag behöver en tidsbeställning hos läkaren.","exampleTranslation":"Ich brauche einen Termin beim Arzt."},
  {"swedish":"sjukskrivning","german":"Krankschreibung","example":"Läkaren gav mig sjukskrivning.","exampleTranslation":"Der Arzt hat mich krankgeschrieben."},
  {"swedish":"bandage","german":"Verband / Bandage","example":"Sjuksköterskan lade på ett bandage.","exampleTranslation":"Die Krankenschwester legte einen Verband an."},
  # More verbs II
  {"swedish":"att planera","german":"planen","example":"Vi planerar en resa till Italien.","exampleTranslation":"Wir planen eine Reise nach Italien."},
  {"swedish":"att bestämma","german":"entscheiden / bestimmen","example":"Vem bestämmer vad vi gör?","exampleTranslation":"Wer entscheidet, was wir tun?"},
  {"swedish":"att jämföra","german":"vergleichen","example":"Jämför priserna innan du köper.","exampleTranslation":"Vergleiche die Preise, bevor du kaufst."},
  {"swedish":"att förbereda","german":"vorbereiten","example":"Jag förbereder mat för imorgon.","exampleTranslation":"Ich bereite Essen für morgen vor."},
  {"swedish":"att fortsätta","german":"weitermachen / fortfahren","example":"Fortsätt läsa boken!","exampleTranslation":"Lies das Buch weiter!"},
  {"swedish":"att hämta","german":"abholen / holen","example":"Kan du hämta barnen från skolan?","exampleTranslation":"Kannst du die Kinder von der Schule abholen?"},
  {"swedish":"att lämna","german":"verlassen / hinterlassen","example":"Lämna ett meddelande om du inte är hemma.","exampleTranslation":"Hinterlass eine Nachricht, wenn du nicht zu Hause bist."},
  {"swedish":"att möta","german":"begegnen / treffen","example":"Jag mötte min gamla vän på gatan.","exampleTranslation":"Ich begegnete meinem alten Freund auf der Straße."},
  {"swedish":"att måla","german":"malen / streichen","example":"Hon målar ett porträtt.","exampleTranslation":"Sie malt ein Porträt."},
  {"swedish":"att sjunka","german":"sinken / untergehen","example":"Solen sjunker i havet.","exampleTranslation":"Die Sonne sinkt ins Meer."},
  # Nature II
  {"swedish":"natur","german":"Natur","example":"Sverige har vacker natur.","exampleTranslation":"Schweden hat schöne Natur."},
  {"swedish":"luft","german":"Luft","example":"Luften är frisk på morgonen.","exampleTranslation":"Die Luft ist morgens frisch."},
  {"swedish":"mark","german":"Boden / Erde (Oberfläche)","example":"Marken är fuktig efter regnet.","exampleTranslation":"Der Boden ist nach dem Regen feucht."},
  {"swedish":"klippa","german":"Fels / Klippe","example":"Vi klättrar på klipporna.","exampleTranslation":"Wir klettern auf den Felsen."},
  {"swedish":"å","german":"Bach / kleiner Fluss","example":"Barnen leker vid ån.","exampleTranslation":"Die Kinder spielen am Bach."},
  {"swedish":"fält","german":"Feld","example":"Det finns blommor på fältet.","exampleTranslation":"Es gibt Blumen auf dem Feld."},
  {"swedish":"buske","german":"Busch / Strauch","example":"Fågeln sitter i busken.","exampleTranslation":"Der Vogel sitzt im Busch."},
  {"swedish":"mossa","german":"Moos","example":"Det växer mossa på stenen.","exampleTranslation":"Moos wächst auf dem Stein."},
  {"swedish":"ö","german":"Insel","example":"Vi bor på en liten ö.","exampleTranslation":"Wir leben auf einer kleinen Insel."},
  {"swedish":"strand","german":"Strand","example":"Vi sitter på stranden.","exampleTranslation":"Wir sitzen am Strand."},
  # Everyday nouns
  {"swedish":"liv","german":"Leben","example":"Livet är vackert.","exampleTranslation":"Das Leben ist schön."},
  {"swedish":"värld","german":"Welt","example":"Det är en stor värld.","exampleTranslation":"Es ist eine große Welt."},
  {"swedish":"sak","german":"Sache / Ding","example":"Vad är det för sak?","exampleTranslation":"Was ist das für eine Sache?"},
  {"swedish":"svar","german":"Antwort","example":"Jag väntar på svaret.","exampleTranslation":"Ich warte auf die Antwort."},
  {"swedish":"fråga","german":"Frage","example":"Jag har en fråga.","exampleTranslation":"Ich habe eine Frage."},
  {"swedish":"problem","german":"Problem","example":"Inget problem!","exampleTranslation":"Kein Problem!"},
  {"swedish":"sanning","german":"Wahrheit","example":"Tala alltid sanning.","exampleTranslation":"Sag immer die Wahrheit."},
  {"swedish":"lögn","german":"Lüge","example":"Det är en lögn.","exampleTranslation":"Das ist eine Lüge."},
  {"swedish":"idé","german":"Idee","example":"Det är en bra idé!","exampleTranslation":"Das ist eine gute Idee!"},
  {"swedish":"plan","german":"Plan","example":"Vad är din plan?","exampleTranslation":"Was ist dein Plan?"},
  # Everyday nouns II
  {"swedish":"röst","german":"Stimme","example":"Hon har en vacker röst.","exampleTranslation":"Sie hat eine schöne Stimme."},
  {"swedish":"ljud","german":"Geräusch / Klang","example":"Vad är det för ljud?","exampleTranslation":"Was ist das für ein Geräusch?"},
  {"swedish":"bild","german":"Bild / Foto","example":"Vi tittar på gamla bilder.","exampleTranslation":"Wir schauen alte Fotos an."},
  {"swedish":"sång","german":"Lied / Gesang","example":"Det är en vacker sång.","exampleTranslation":"Das ist ein schönes Lied."},
  {"swedish":"historia","german":"Geschichte","example":"Berätta en rolig historia!","exampleTranslation":"Erzähl eine lustige Geschichte!"},
  {"swedish":"saga","german":"Märchen","example":"Mormor berättar sagor.","exampleTranslation":"Oma erzählt Märchen."},
  {"swedish":"dröm","german":"Traum","example":"Jag hade en konstig dröm.","exampleTranslation":"Ich hatte einen seltsamen Traum."},
  {"swedish":"mål","german":"Ziel","example":"Mitt mål är att lära mig svenska.","exampleTranslation":"Mein Ziel ist es, Schwedisch zu lernen."},
  {"swedish":"hopp","german":"Hoffnung","example":"Det finns alltid hopp.","exampleTranslation":"Es gibt immer Hoffnung."},
  {"swedish":"minne","german":"Erinnerung / Gedächtnis","example":"Det är ett fint minne.","exampleTranslation":"Das ist eine schöne Erinnerung."},
  # Household verbs
  {"swedish":"att diska","german":"abwaschen / spülen","example":"Kan du diska efter maten?","exampleTranslation":"Kannst du nach dem Essen abwaschen?"},
  {"swedish":"att dammsuga","german":"staubsaugen","example":"Jag dammsuger rummet.","exampleTranslation":"Ich sauge das Zimmer."},
  {"swedish":"att stryka","german":"bügeln","example":"Jag stryker skjortorna.","exampleTranslation":"Ich bügle die Hemden."},
  {"swedish":"att vattna","german":"gießen (Pflanzen)","example":"Kom ihåg att vattna blommorna.","exampleTranslation":"Vergiss nicht, die Blumen zu gießen."},
  {"swedish":"att klippa","german":"schneiden / mähen","example":"Jag klipper gräset på lördag.","exampleTranslation":"Ich mähe den Rasen am Samstag."},
  {"swedish":"att rensa","german":"aufräumen / reinigen","example":"Rensa bordet efter maten.","exampleTranslation":"Räum den Tisch nach dem Essen ab."},
  {"swedish":"att sortera","german":"sortieren","example":"Sortera soporna i rätt papperskorg.","exampleTranslation":"Sortiere den Müll in die richtige Tonne."},
  {"swedish":"att kasta","german":"werfen / wegwerfen","example":"Kasta inte mat!","exampleTranslation":"Wirf kein Essen weg!"},
  {"swedish":"att packa","german":"packen","example":"Jag packar väskan inför resan.","exampleTranslation":"Ich packe die Tasche für die Reise."},
  {"swedish":"att måla","german":"malen / streichen (Wand)","example":"Vi målar väggarna vita.","exampleTranslation":"Wir streichen die Wände weiß."},
  # Food preparation
  {"swedish":"att baka","german":"backen","example":"Vi bakar bröd på söndag.","exampleTranslation":"Wir backen sonntags Brot."},
  {"swedish":"att koka","german":"kochen (sieden)","example":"Koka pastan i tio minuter.","exampleTranslation":"Koche die Nudeln zehn Minuten."},
  {"swedish":"att steka","german":"braten / anbraten","example":"Stek köttbullarna i smör.","exampleTranslation":"Brate die Hackbällchen in Butter."},
  {"swedish":"att grilla","german":"grillen","example":"Vi grillar korv på midsommar.","exampleTranslation":"Wir grillen Würstchen zu Mittsommer."},
  {"swedish":"ingrediens","german":"Zutat","example":"Vilka ingredienser behövs?","exampleTranslation":"Welche Zutaten werden benötigt?"},
  {"swedish":"portion","german":"Portion","example":"En portion räcker.","exampleTranslation":"Eine Portion reicht."},
  {"swedish":"smak","german":"Geschmack","example":"Maten har god smak.","exampleTranslation":"Das Essen hat einen guten Geschmack."},
  {"swedish":"att smaka","german":"schmecken / kosten","example":"Smaka på soppan!","exampleTranslation":"Koste die Suppe!"},
  {"swedish":"fryst","german":"gefroren / tiefgefroren","example":"Jag köper fryst fisk.","exampleTranslation":"Ich kaufe Tiefkühlfish."},
  {"swedish":"färsk","german":"frisch","example":"Jag köper alltid färskt bröd.","exampleTranslation":"Ich kaufe immer frisches Brot."},
  # Quantity words
  {"swedish":"ett par","german":"ein Paar / ein paar","example":"Jag behöver ett par minuter.","exampleTranslation":"Ich brauche ein paar Minuten."},
  {"swedish":"mängd","german":"Menge","example":"Det finns en stor mängd folk.","exampleTranslation":"Es gibt eine große Menge Menschen."},
  {"swedish":"antal","german":"Anzahl","example":"Vilket antal vill du ha?","exampleTranslation":"Welche Anzahl möchtest du?"},
  {"swedish":"tillräckligt","german":"genug / ausreichend","example":"Jag har tillräckligt med pengar.","exampleTranslation":"Ich habe genug Geld."},
  {"swedish":"för mycket","german":"zu viel","example":"Det är för mycket socker i kakan.","exampleTranslation":"Es ist zu viel Zucker im Kuchen."},
  {"swedish":"för lite","german":"zu wenig","example":"Det finns för lite mat.","exampleTranslation":"Es gibt zu wenig Essen."},
  {"swedish":"lagom","german":"genau richtig / angemessen","example":"Det är lagom varmt idag.","exampleTranslation":"Es ist heute genau richtig warm."},
  {"swedish":"fullt","german":"voll","example":"Glaset är fullt.","exampleTranslation":"Das Glas ist voll."},
  {"swedish":"tomt","german":"leer","example":"Kylen är tom.","exampleTranslation":"Der Kühlschrank ist leer."},
  {"swedish":"halvt","german":"halb","example":"Jag vill ha ett halvt glas.","exampleTranslation":"Ich möchte ein halbes Glas."},
  # Computer / digital
  {"swedish":"laptop","german":"Laptop","example":"Jag jobbar med min laptop.","exampleTranslation":"Ich arbeite mit meinem Laptop."},
  {"swedish":"surfplatta","german":"Tablet","example":"Barnet spelar spel på surfplattan.","exampleTranslation":"Das Kind spielt Spiele auf dem Tablet."},
  {"swedish":"laddare","german":"Ladekabel / Ladegerät","example":"Har du laddat laddaren?","exampleTranslation":"Hast du den Ladestecker?"},
  {"swedish":"batteri","german":"Batterie / Akku","example":"Batteriet är snart slut.","exampleTranslation":"Der Akku ist bald leer."},
  {"swedish":"wifi","german":"WLAN / WiFi","example":"Vad är lösenordet till wifi?","exampleTranslation":"Was ist das WLAN-Passwort?"},
  {"swedish":"lösenord","german":"Passwort","example":"Glöm inte ditt lösenord!","exampleTranslation":"Vergiss dein Passwort nicht!"},
  {"swedish":"att söka","german":"suchen","example":"Jag söker information på internet.","exampleTranslation":"Ich suche Informationen im Internet."},
  {"swedish":"att ladda ner","german":"herunterladen","example":"Ladda ner appen gratis.","exampleTranslation":"Lade die App kostenlos herunter."},
  {"swedish":"att ladda upp","german":"hochladen","example":"Jag laddar upp bilden.","exampleTranslation":"Ich lade das Bild hoch."},
  {"swedish":"sociala medier","german":"soziale Medien","example":"Jag använder sociala medier varje dag.","exampleTranslation":"Ich nutze soziale Medien jeden Tag."},
  # Adjectives II
  {"swedish":"populär","german":"populär / beliebt","example":"Den här sången är populär.","exampleTranslation":"Dieses Lied ist beliebt."},
  {"swedish":"vanlig","german":"gewöhnlich / normal / häufig","example":"Det är en vanlig dag.","exampleTranslation":"Es ist ein gewöhnlicher Tag."},
  {"swedish":"ovanlig","german":"ungewöhnlich / selten","example":"Det är ett ovanligt namn.","exampleTranslation":"Das ist ein ungewöhnlicher Name."},
  {"swedish":"möjlig","german":"möglich","example":"Det är möjligt att lära sig svenska.","exampleTranslation":"Es ist möglich, Schwedisch zu lernen."},
  {"swedish":"omöjlig","german":"unmöglich","example":"Det är inte omöjligt!","exampleTranslation":"Das ist nicht unmöglich!"},
  {"swedish":"nödvändig","german":"notwendig / nötig","example":"Det är nödvändigt att sova.","exampleTranslation":"Es ist notwendig zu schlafen."},
  {"swedish":"onödig","german":"unnötig","example":"Det är onödigt att oroa sig.","exampleTranslation":"Es ist unnötig, sich zu sorgen."},
  {"swedish":"perfekt","german":"perfekt","example":"Vädret är perfekt idag!","exampleTranslation":"Das Wetter ist heute perfekt!"},
  {"swedish":"fel","german":"falsch / Fehler","example":"Det är fel svar.","exampleTranslation":"Das ist die falsche Antwort."},
  {"swedish":"rätt","german":"richtig","example":"Det är rätt svar!","exampleTranslation":"Das ist die richtige Antwort!"},
  # Remaining
  {"swedish":"granne","german":"Nachbar / Nachbarin","example":"Min granne är mycket trevlig.","exampleTranslation":"Mein Nachbar ist sehr nett."},
  {"swedish":"lag","german":"Mannschaft / Team","example":"Vilket lag tycker du om?","exampleTranslation":"Welche Mannschaft magst du?"},
  {"swedish":"match","german":"Spiel / Match","example":"Vi ser matchen på TV.","exampleTranslation":"Wir schauen das Spiel im Fernsehen."},
]

# Load existing data
with open("app/data/vocabulary/a1.json", encoding="utf-8") as f:
    data = json.load(f)

existing_swedish = {w["swedish"].lower() for w in data["words"]}
next_id = len(data["words"]) + 1

added = []
skipped = []
for word in NEW_WORDS:
    key = word["swedish"].lower()
    if key in existing_swedish:
        skipped.append(word["swedish"])
        continue
    entry = {
        "id": f"a1_{next_id:03d}",
        "swedish": word["swedish"],
        "german": word["german"],
        "example": word["example"],
        "exampleTranslation": word["exampleTranslation"],
    }
    data["words"].append(entry)
    existing_swedish.add(key)
    next_id += 1
    added.append(word["swedish"])

with open("app/data/vocabulary/a1.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added: {len(added)}, Skipped (duplicates): {len(skipped)}, Total: {len(data['words'])}")
if skipped:
    print("Skipped:", skipped)
